// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;
using GalaSoft.MvvmLight.Helpers;
using NativeTextDemo.ViewModel;
using UIKit;
using Styles.Text;

namespace NativeTextDemo.iOS
{
    public partial class MainViewController : UIViewController
    {
        StyleManager styleManager;

        // Keep track of bindings to avoid premature garbage collection
        readonly List<Binding> bindings = new List<Binding>();
        MainViewModel Vm
        {
            get
            {
                return Application.Locator.Main;
            }
        }

        public MainViewController(IntPtr handle) : base(handle)
        {
        }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            bindings.Add(
                this.SetBinding(
                  () => Vm.TitleOne,
                  () => titleOne.Text));

            bindings.Add(
                this.SetBinding(
                  () => Vm.TitleTwo,
                  () => titleTwo.Text));

            bindings.Add(
                this.SetBinding(
                  () => Vm.TitleThree,
                    () => titleThree.Text));

            bindings.Add(
                this.SetBinding(
                  () => Vm.Body,
                  () => textBody.Text));

            styleManager = new StyleManager();
            var styleOne = styleManager.Add(titleOne, TextStyles.H1);

            styleManager.Add(titleTwo, TextStyles.H2);
            styleManager.Add(titleThree, TextStyles.H1);
            styleManager.Add(textBody, TextStyles.Body);
        }
    }
}
