#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("NativeTextDemo.Droid.Resource", IsApplication=true)]

namespace NativeTextDemo.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Styles.Resource.String.library_name = global::NativeTextDemo.Droid.Resource.String.library_name;
			global::Styles.Text.Droid.Resource.String.library_name = global::NativeTextDemo.Droid.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070000
			public const int layout = 2131165184;
			
			// aapt resource value: 0x7f070008
			public const int menu_refresh = 2131165192;
			
			// aapt resource value: 0x7f070007
			public const int space1 = 2131165191;
			
			// aapt resource value: 0x7f070005
			public const int textBody = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int textEdit = 2131165190;
			
			// aapt resource value: 0x7f070002
			public const int titleOne = 2131165186;
			
			// aapt resource value: 0x7f070004
			public const int titleThree = 2131165188;
			
			// aapt resource value: 0x7f070003
			public const int titleTwo = 2131165187;
			
			// aapt resource value: 0x7f070001
			public const int toolbar = 2131165185;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int toolbar = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int home = 2131099648;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_cached_white_24dp = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int app_name = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int hello = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int MyTheme = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
